/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-14 09:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1670554267434L));
    _jspx_dependants.put("jar:file:/D:/JSP_test/JSP_Yeseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/YeseonLim/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>home page</title>\n");
      out.write("<link href=\"/resources/all.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		<div class=\"left\">\n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"#main\">Home</a></li>\n");
      out.write("				<li><a href=\"#about\">About</a></li>\n");
      out.write("				<li><a href=\"#experience\">Experience</a></li>\n");
      out.write("				<li><a href=\"#whatilove\">What i love</a></li>\n");
      out.write("				<li><a href=\"#guestbook\">Guest Book</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	<section id=main>\n");
      out.write("		<div class=\"right\">\n");
      out.write("				<div class=\"content1\">\n");
      out.write("				<h1></h1>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	</header>\n");
      out.write("	<section id=about>\n");
      out.write("	<div class=\"right\">\n");
      out.write("			<div class=\"pic\">\n");
      out.write("				<img alt=\"\" src=\"/resources/img/me.jpg\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"info\">\n");
      out.write("				<ul class=\"detail\">\n");
      out.write("					<li>NAME | 임예선</li>\n");
      out.write("					<li>BIRTH | 1995.09.04</li>\n");
      out.write("					<li>CONTACT | 010-4108-9528</li>\n");
      out.write("					<li>EMAIL | tkdzma6228@naver.com</li>\n");
      out.write("					<li>MBTI | ISFP</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<section id=\"experience\">\n");
      out.write("		<div class=\"right\">\n");
      out.write("		<h1> What I Achieved </h1>\n");
      out.write("			<div class=\"content3\">\n");
      out.write("            	<input type=\"checkbox\" id=\"popup\">\n");
      out.write("               	<label for=\"popup\">HighSchool</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup\"></label>\n");
      out.write("	                     <img src=\"/resources/img/high.jpg\" alt=\"\" width=\"700px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup1\">\n");
      out.write("               	<label for=\"popup1\">University</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup1\"></label>\n");
      out.write("	                     <img src=\"/resources/img/uni.jpg\" alt=\"\" width=\"700px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup1\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup2\">\n");
      out.write("               	<label for=\"popup2\">Airline</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup2\"></label>\n");
      out.write("	                     <img src=\"/resources/img/kal.jpg\" alt=\"\" width=\"300px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup2\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup3\">\n");
      out.write("               	<label for=\"popup3\">NewZealand</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup3\"></label>\n");
      out.write("	                     <img src=\"/resources/img/new.jpg\" alt=\"\" width=\"700px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup3\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup4\">\n");
      out.write("               	<label for=\"popup4\">MedicalCenter</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup4\"></label>\n");
      out.write("	                     <img src=\"/resources/img/hos.jpg\" alt=\"\" width=\"300px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup4\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup5\">\n");
      out.write("               	<label for=\"popup5\">Academy</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup5\"></label>\n");
      out.write("	                     <img src=\"/resources/img/cube.jpg\" alt=\"\" width=\"300px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup5\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup6\">\n");
      out.write("               	<label for=\"popup6\">BackToStudent</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup6\"></label>\n");
      out.write("	                     <img src=\"/resources/img/ezen.jpg\" alt=\"\" width=\"700px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup6\">X</label>\n");
      out.write("	               </div>\n");
      out.write("            	<input type=\"checkbox\" id=\"popup7\">\n");
      out.write("               	<label for=\"popup7\">MyNextPage</label>\n");
      out.write("	               <div>\n");
      out.write("	                  <div>\n");
      out.write("	                     <label for=\"popup7\"></label>\n");
      out.write("	                     <img src=\"/resources/img/view.jpg\" alt=\"\" width=\"700px\" height=\"500px\">\n");
      out.write("	                  </div>\n");
      out.write("	               <label for=\"popup7\">X</label>\n");
      out.write("	               </div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<section id=\"whatilove\">\n");
      out.write("		<div class=\"right\">\n");
      out.write("		<h1> What I Love </h1>\n");
      out.write("			<div class=\"slide_wrapper\">\n");
      out.write("				<ul class=\"slides\">\n");
      out.write("				<li><img alt=\"family\" src=\"/resources/img/fam.jpg\"><strong>가족</strong></li>\n");
      out.write("				<li><img alt=\"travel\" src=\"/resources/img/travel.jpg\"><strong>여행</strong></li>\n");
      out.write("				<li><img alt=\"doctorwho\" src=\"/resources/img/doctor.gif\"><strong>닥터후</strong></li>\n");
      out.write("				<li><img alt=\"yangyang\" src=\"/resources/img/yang.jpg\"><strong>양양</strong></li>\n");
      out.write("				<li><img alt=\"learn\" src=\"/resources/img/learn.jpg\"><strong>배우는재미</strong></li>\n");
      out.write("				<li><img alt=\"baking\" src=\"/resources/img/bak.jpg\"><strong>제빵</strong></li>\n");
      out.write("				<li><img alt=\"chilling\" src=\"/resources/img/chilling.jpg\"><strong>즐거운한잔</strong></li>\n");
      out.write("				<li><img alt=\"food\" src=\"/resources/img/food.jpg\"><strong>맛있는것</strong></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<p class=\"controls\">\n");
      out.write("			<span class=\"prev\"> << </span>\n");
      out.write("			<span class=\"next\"> >> </span>\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<section id=\"guestbook\">\n");
      out.write("		<div class=\"right\">\n");
      out.write("		<h1> 방명록 </h1>\n");
      out.write("			<div class=\"content5\">\n");
      out.write("				<form action=\"/gbc/insert\" method=\"post\">\n");
      out.write("					작성자 : <input type=\"text\" name=\"writer\"><br>\n");
      out.write("					내용 : <textarea rows=\"1\" cols=\"70\" name=\"content\" ></textarea>\n");
      out.write("					<button type=\"submit\"> 등록 </button><br>\n");
      out.write("				</form>\n");
      out.write("				<hr>\n");
      out.write("				<table>\n");
      out.write("					<tr>\n");
      out.write("						<th>번호</th>\n");
      out.write("						<th>작성자</th>\n");
      out.write("						<th>내용</th>\n");
      out.write("						<th>작성일</th>\n");
      out.write("					</tr>\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<script src=\"/resources/main.js\" type=\"text/javascript\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index.jsp(163,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(163,5) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /index.jsp(163,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("gvo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					<tr>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gvo.gno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gvo.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gvo.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gvo.reg_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					</tr>\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
